services:
  - type: web
    name: saferoute-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    repo: https://github.com/yourusername/saferoute
    branch: main
    plan: free
    rootDir: api
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: saferoute-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    repo: https://github.com/yourusername/saferoute
    branch: main
    plan: free
    rootDir: web
    envVars:
      - key: NODE_VERSION
        value: 19
